def KEYS():
    CONSUMER_KEY = 'ZXbM2vxRLwu3ZrenMBl1ZILe1'
    CONSUMER_SECRET = 'nbfyN3SfMrrerqTFFCfOuFjECy2lRqfmxwJrivqx2CxnpbAuH7'
    ACCESS_KEY= '296906916-xiWeizroDnU5p60XG9YzzRy0fe4v9XqxTSFshWa6'
    ACCESS_SECRET = 'sJi0jI3YdkJTSDZ2tYFosHVqFhM2ksXnaAZMML0V1eBB9'
    return [CONSUMER_KEY,CONSUMER_SECRET,ACCESS_KEY,ACCESS_SECRET] 
